export enum ActeVeterinaireEnum {
  STERILISATION = 'STERILISATION',

  IDENTIFICATION = 'IDENTIFICATION',

  VACCINATION_TL = 'VACCINATION_TL',
  VACCINATION_TLC = 'VACCINATION_TLC',
  VACCINATION_TL_PRIMO = 'VACCINATION_TL_PRIMO',
  VACCINATION_TLC_PRIMO = 'VACCINATION_TLC_PRIMO',

  DEPARASITAGE = 'DEPARASITAGE',
  ANTIPUCE_ANTI_TIQUE = 'ANTIPUCE_ANTI_TIQUE',

  VERMIFUGATION = 'VERMIFUGATION',

  OPERATION = 'OPERATION',
  AUTRES = 'AUTRES',
}
